// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "provider": string;
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "sendPaperContextToKisski": boolean;
      "contextRouterProvider": string;
      "embeddingSearchEnabled": boolean;
      "embeddingBaseUrl": string;
      "embeddingModel": string;
      "ollamaBaseUrl": string;
      "ollamaModel": string;
      "maxItems": number;
      "metadataFieldSelection": string;
      "autoDeleteOldChats": boolean;
      "initialIndexPromptShown": boolean;
      "chunkTargetTokens": number;
      "chunkOverlapTokens": number;
      "chunkCount": number;
    };
  }
}
