// Generated by zotero-plugin-scaffold
// Manual comments in this file may be replaced when scaffold typings are regenerated.
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// Extends Zotero's preference types so getPref/setPref can infer the value type
// belonging to each ZAIA preference key.
// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      // Chat provider connection and model selection.
      "provider": string;
      "apiKey": string;
      "baseUrl": string;
      "model": string;

      // Privacy and routing choices for requests that include paper context.
      "sendPaperContextToKisski": boolean;
      "contextRouterProvider": string;

      // Semantic search and its local Ollama embedding model.
      "embeddingSearchEnabled": boolean;
      "embeddingModel": string;

      // Local Ollama connection used by locally hosted models.
      "ollamaBaseUrl": string;
      "ollamaModel": string;

      // Library indexing scope and metadata included in retrieval.
      "maxItems": number;
      "metadataFieldSelection": string;

      // Chat retention and one-time setup state.
      "autoDeleteOldChats": boolean;
      "initialIndexPromptShown": boolean;

      // Chunk construction and retrieval budgets.
      "chunkTargetTokens": number;
      "chunkOverlapTokens": number;
      "chunkCount": number;
    };
  }
}
